/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuahanganphuoc.GUI.admin;

import cuahanganphuoc.DAO.KhachHangDAO;
import cuahanganphuoc.DAO.MauSacDAO;
import cuahanganphuoc.MODAL.MAUSAC;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class frmMauSac extends javax.swing.JFrame {
    List<MAUSAC> list = new ArrayList<>();
    DefaultTableModel tblModel = new DefaultTableModel();
    int TrangThai=0;
    /**
     * Creates new form frmMauSac
     */
    public frmMauSac() {
        initComponents();
        initTable();
        tblMauSac.setDefaultEditor(Object.class, null);
        tblMauSac.setSelectionMode(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMauSac = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaMau = new javax.swing.JTextField();
        txtTenMau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMauSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã màu", "Tên màu"
            }
        ));
        tblMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMauSacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMauSac);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 391, 393));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/add1.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 126, 66));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/data-processing.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 129, 66));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 120, 66));

        jLabel1.setText("Mã màu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel2.setText("Tên màu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));
        getContentPane().add(txtMaMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 171, -1));
        getContentPane().add(txtTenMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 171, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("QUẢN LÝ MÀU SẮC");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 490, 74));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1330, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(TrangThai!=1){
            TrangThai=1;
            txtMaMau.setText("");
            txtTenMau.setText("");
            MauSacDAO.loadAll();
            txtMaMau.setText(MauSacDAO.taoMaKHMoi());
            return;
        }
        try{
            validateInputs();
        } catch(Exception e ){
            return;
        }
        String ma = txtMaMau.getText().toString();
        String ten = txtTenMau.getText().toString();
        MauSacDAO  dao = new MauSacDAO();
        if(dao.themMauSac(ma,ten)){
            JOptionPane.showMessageDialog(this, "INSERT THANH CONG");
            Clear();
        }else {
            JOptionPane.showMessageDialog(this, "insert that bai");
        }
        initTable();
        TrangThai=0;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng UPDATE");
            return;
        }
        try{
            validateInputs();
        } catch(Exception e ){
            return;
        }
        String ma = txtMaMau.getText();
        String ten = txtTenMau.getText();
        MauSacDAO dao = new MauSacDAO();
        if (dao.suaMauSac(ten,ma)) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            Clear();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        initTable();
        TrangThai=0;
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng DELETE");
            return;
        }
        String ma = txtMaMau.getText();
        MauSacDAO dao = new MauSacDAO();
        if (dao.xoaMauSac(ma)) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            Clear();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
        initTable();
        TrangThai=0;
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMauSacMouseClicked
        // TODO add your handling code here:
        int row = tblMauSac.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblMauSac.getModel();
        txtMaMau.setText(model.getValueAt(row, 0).toString());
        txtTenMau.setText(model.getValueAt(row, 1).toString());
        TrangThai=2;
    }//GEN-LAST:event_tblMauSacMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMauSac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMauSac;
    private javax.swing.JTextField txtMaMau;
    private javax.swing.JTextField txtTenMau;
    // End of variables declaration//GEN-END:variables
    public void initTable() {
        MauSacDAO msdao = new MauSacDAO();
        list = msdao.layDanhSachMAUSAC();
        tblModel = (DefaultTableModel) tblMauSac.getModel();
        tblModel.setRowCount(0);  // Clear existing rows

        for (MAUSAC mauSac : list) {
            Object[] row = new Object[]{
                mauSac.getMaMS(), 
                mauSac.getTenMS()
            };
            tblModel.addRow(row);
        }

        tblMauSac.setModel(tblModel);
    }
     public void Clear(){
        txtMaMau.setText("");
        txtTenMau.setText("");
        txtMaMau.requestFocus();
    }
     void validateInputs() {
        String ma = txtMaMau.getText().trim();
         String ten = txtTenMau.getText().trim();
    
         if (ma.isEmpty() || ten.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        throw new IllegalArgumentException("Vui lòng nhập đủ thông tin.");
         }
    }

}
