/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuahanganphuoc.GUI.admin;

import cuahanganphuoc.DAO.KhachHangDAO;
import cuahanganphuoc.DAO.SizeDAO;
import cuahanganphuoc.MODAL.LUUTRU;
import cuahanganphuoc.MODAL.SIZE;
import cuahanganphuoc.MODAL.USER;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frmSize extends javax.swing.JFrame {
int TrangThai=0;
    /**
     * Creates new form frmSize
     */
    public frmSize() {
        initComponents();
        initBanDau();
        tbSize.setDefaultEditor(Object.class, null);
        tbSize.setSelectionMode(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSize = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/data-processing.png"))); // NOI18N
        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 109, 67));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 112, 67));

        jLabel1.setText("Mã size");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));

        jLabel2.setText("Tên size");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));
        getContentPane().add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 138, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 135, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản lý size");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 781, 57));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/add1.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 106, 67));

        tbSize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSizeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSize);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 370, 454));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1240, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(TrangThai!=1){
            TrangThai=1;
            txtMa.setText("");
            txtName.setText("");
            SizeDAO.loadAll();
            txtMa.setText(SizeDAO.taoMaKHMoi());
            return;
        }
        try{
            validateInputs();
        } catch(Exception e ){
            return;
        }
        String ten = txtName.getText();
        String ma = txtMa.getText();

        SIZE u = new SIZE(ma, ten);

        if(!SizeDAO.themCSDL(u))
        {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
            return;
        }
        SizeDAO.loadAll();
        clear();
        loadSP();
        TrangThai=0;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng DELETE");
            return;
        }
        String ma = txtMa.getText();
        SIZE u = new SIZE(ma, "");
        if(!SizeDAO.xoaCSDL(u))
        {
            JOptionPane.showMessageDialog(this, "Xoá thất bại");
            return;
        }
        SizeDAO.loadAll();
        clear();
        loadSP();
        TrangThai=0;
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng UPDATE");
            return;
        }
        try{
            validateInputs();
        } catch(Exception e ){
            return;
        }
        String ten = txtName.getText();
        String ma = txtMa.getText();

        SIZE u = new SIZE(ma, ten);

        if(!SizeDAO.capNhatCSDL(u))
        {
            JOptionPane.showMessageDialog(this, "Sua thất bại");
            return;
        }
        SizeDAO.loadAll();
        clear();
        loadSP();
        TrangThai=0;
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSizeMouseClicked
        int row = tbSize.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbSize.getModel();
        txtName.setText(""+model.getValueAt(row, 1));
        txtMa.setText(""+model.getValueAt(row, 0));
        TrangThai=2;
    }//GEN-LAST:event_tbSizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSize;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    void initBanDau(){
        
        SizeDAO.loadAll();
        tbSize.setDefaultEditor(Object.class, null);
        tbSize.setSelectionMode(0);
        loadSP();
        
    }
    private void loadSP() {
        DefaultTableModel model = new DefaultTableModel();
        Vector data = new Vector();
        Vector<String> tieuDe = new Vector<String>();
        tieuDe.add("Ma Size");
        tieuDe.add("Ten Size");

        List<SIZE> dsMA = LUUTRU.listSize;
        for (SIZE sz : dsMA) {
            String ma = sz.getMa();
            String ten = sz.getTen();
            Vector<Object> v = new Vector<>();
            v.add(ma);
            v.add(ten);
            data.add(v);
        }

        if (data != null) {
            model.setDataVector(data, tieuDe);
        }
        tbSize.setModel(model);
        clear();
    }
    void clear(){
        txtName.setText("");
        txtMa.setText("");
    }
    void validateInputs() {
        String ma = txtMa.getText().trim();
         String ten = txtName.getText().trim();
    
         if (ma.isEmpty() || ten.isEmpty() ) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        throw new IllegalArgumentException("Vui lòng nhập đủ thông tin.");
         }
    }
}
