/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuahanganphuoc.GUI.admin;

import cuahanganphuoc.DAO.ChatLieuDAO;
import cuahanganphuoc.DAO.KhachHangDAO;
import cuahanganphuoc.DAO.KieuDangDAO;
import cuahanganphuoc.DAO.LoaiSPDAO;
import cuahanganphuoc.DAO.MauSacDAO;
import cuahanganphuoc.DAO.SanPhamDAO;
import cuahanganphuoc.DAO.SizeDAO;
import cuahanganphuoc.DAO.ThamChieuDAO;
import cuahanganphuoc.MODAL.CHATLIEU;
import cuahanganphuoc.MODAL.KIEUDANG;
import cuahanganphuoc.MODAL.LOAISP;
import cuahanganphuoc.MODAL.LUUTRU;
import cuahanganphuoc.MODAL.MAUSAC;
import cuahanganphuoc.MODAL.SANPHAM;
import cuahanganphuoc.MODAL.SIZE;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frmSanPham extends javax.swing.JFrame {

    String tenHinh = "";
    int TrangThai=0;
    /**
     * Creates new form frmSanPham
     */
    public frmSanPham() {
        initComponents();
        initBanDau();
        tbSP.setDefaultEditor(Object.class, null);
        tbSP.setSelectionMode(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboChatLieu = new javax.swing.JComboBox<>();
        cboSize = new javax.swing.JComboBox<>();
        txtSoLuong = new javax.swing.JTextField();
        cboKieuDang = new javax.swing.JComboBox<>();
        cboLoaiSanPham = new javax.swing.JComboBox<>();
        btnChonHinh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSP = new javax.swing.JTable();
        cboMauSac = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản lý sản phẩm");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/add1.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/delete.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/data-processing.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã sản phẩm");

        jLabel4.setText("Tên sản phẩm");

        jLabel6.setText("Giá bán");

        jLabel7.setText("Trạng thái");

        jLabel8.setText("Loại sản phẩm");

        jLabel9.setText("Chất liệu");

        jLabel10.setText("Kiểu dáng");

        jLabel11.setText("Số lượng");

        jLabel12.setText("Size");

        btnChonHinh.setText("Chọn ảnh");
        btnChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHinhActionPerformed(evt);
            }
        });

        tbSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbSP);

        jLabel2.setText("Màu sắc");

        jPanel1.setMaximumSize(new java.awt.Dimension(254, 174));
        jPanel1.setMinimumSize(new java.awt.Dimension(254, 174));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblHinh.setMaximumSize(new java.awt.Dimension(254, 174));
        lblHinh.setMinimumSize(new java.awt.Dimension(254, 174));
        jPanel1.add(lblHinh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 41, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel12)))
                                        .addGap(45, 45, 45)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboKieuDang, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnChonHinh)
                                        .addGap(73, 73, 73))))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChonHinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboKieuDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHinhActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Images(*.png;*.jpg;*.jpeg;*.gif;*.webp)", "png", "jpg", "jpeg", "gif", "webp");
            fileChooser.addChoosableFileFilter(filter);
            fileChooser.setAcceptAllFileFilterUsed(false);
            int kt = fileChooser.showOpenDialog(null);
            if (kt == JFileChooser.APPROVE_OPTION) {
                File f = fileChooser.getSelectedFile();
                tenHinh = f.getName();
                String location = "src/cuahanganphuoc/icon/" + tenHinh;
                File destinationF = new File(location);

                File desF = new File(location);
                if (!desF.exists()) {
                    Files.copy(f.toPath(), destinationF.toPath());
                }

                ImageIcon hinh = new ImageIcon(new ImageIcon(location).getImage().getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_DEFAULT));
                lblHinh.setIcon(hinh);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChonHinhActionPerformed

    private void tbSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSPMouseClicked
        int row = tbSP.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbSP.getModel();
        txtMa.setText((String) model.getValueAt(row, 0));
        txtTen.setText((String) model.getValueAt(row, 1));
        txtGia.setText(model.getValueAt(row, 2) + "");
        tenHinh = (String) model.getValueAt(row, 9);
        txtSoLuong.setText(model.getValueAt(row, 3).toString());
        ImageIcon hinh = new ImageIcon(new ImageIcon("src/cuahanganphuoc/icon/" + tenHinh).getImage().getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_DEFAULT));
        lblHinh.setIcon(hinh);
        txtTrangThai.setText(model.getValueAt(row, 4).toString());
        
        String size = model.getValueAt(row, 5).toString();
        String chatlieu = model.getValueAt(row, 7).toString();
        String kieudang = model.getValueAt(row, 6).toString();
        String mausac = model.getValueAt(row, 8).toString();
        String loai = model.getValueAt(row, 10).toString();
        SIZE s = ThamChieuDAO.getSIZEbyTENSIZE(size);
        CHATLIEU cl = ThamChieuDAO.getCHATLIEUbyTENCHATLIEU(chatlieu);
        KIEUDANG kd = ThamChieuDAO.getKIEUDANGbyTENKIEUDANG(kieudang);
        MAUSAC ms = ThamChieuDAO.getMAUSACbyTENMAUSAC(mausac);
        LOAISP lsp = ThamChieuDAO.getLOAISPCbyTENLOAISP(loai);
        cboSize.setSelectedItem(s);
        cboChatLieu.setSelectedItem(cl);
        cboMauSac.setSelectedItem(ms);
        cboKieuDang.setSelectedItem(kd);
        cboLoaiSanPham.setSelectedItem(lsp);
        TrangThai=2;
    }//GEN-LAST:event_tbSPMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(TrangThai!=1){
            TrangThai=1;
            txtMa.setText("");
            txtTen.setText("");
            txtGia.setText("");
            txtTrangThai.setText("");
            txtSoLuong.setText("");
            SanPhamDAO.loadAll();
            txtMa.setText(SanPhamDAO.taoMaKHMoi());
            return;
        }
        try{
            validateInputs();
        } catch(Exception e ){
            return;
        }
        String ten = txtTen.getText();
        String ma = txtMa.getText();
        int gia = Integer.parseInt(txtGia.getText());
        int sl = Integer.parseInt(txtSoLuong.getText());
        int tt = Integer.parseInt(txtTrangThai.getText());

        
        String size = ((SIZE)cboSize.getSelectedItem()).getMa();
        String kd = ((KIEUDANG)cboKieuDang.getSelectedItem()).getMaKD();
        String cl = ((CHATLIEU)cboChatLieu.getSelectedItem()).getMaCL();
        String ms = ((MAUSAC)cboMauSac.getSelectedItem()).getMaMS();
        String lsp = ((LOAISP)cboLoaiSanPham.getSelectedItem()).getMaLoai();

        SANPHAM u = new SANPHAM(ma, ten, lsp, ms, cl, kd, tenHinh, size, gia, tt, sl);

        if(!SanPhamDAO.themCSDL(u))
        {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
            return;
        }
        SanPhamDAO.loadAll();
        clear();
        loadSP();
        TrangThai=0;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng DELETE");
            return;
        }
        String ma = txtMa.getText();
        if(SanPhamDAO.xoaCSDL(ma)){
            JOptionPane.showMessageDialog(this, "THANH CONG");
        }else JOptionPane.showMessageDialog(this, "THAT BAI");
        SanPhamDAO.loadAll();
        loadSP();
        TrangThai=0;
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng UPDATE");
            return;
        }
        try{
            validateInputs();
        } catch(Exception e ){
            return;
        }
        String ten = txtTen.getText();
        String ma = txtMa.getText();
        int gia = Integer.parseInt(txtGia.getText());
        int sl = Integer.parseInt(txtSoLuong.getText());
        int tt = Integer.parseInt(txtTrangThai.getText());

        
        String size = ((SIZE)cboSize.getSelectedItem()).getMa();
        String kd = ((KIEUDANG)cboKieuDang.getSelectedItem()).getMaKD();
        String cl = ((CHATLIEU)cboChatLieu.getSelectedItem()).getMaCL();
        String ms = ((MAUSAC)cboMauSac.getSelectedItem()).getMaMS();
        String lsp = ((LOAISP)cboLoaiSanPham.getSelectedItem()).getMaLoai();

        SANPHAM u = new SANPHAM(ma, ten, lsp, ms, cl, kd, tenHinh, size, gia, tt, sl);

        if(!SanPhamDAO.capNhatCSDL(u))
        {
            JOptionPane.showMessageDialog(this, "THAI BAI");
            return;
        }
        SanPhamDAO.loadAll();
        clear();
        loadSP();
        TrangThai=0;
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonHinh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<CHATLIEU> cboChatLieu;
    private javax.swing.JComboBox<KIEUDANG> cboKieuDang;
    private javax.swing.JComboBox<LOAISP> cboLoaiSanPham;
    private javax.swing.JComboBox<MAUSAC> cboMauSac;
    private javax.swing.JComboBox<SIZE> cboSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JTable tbSP;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
    void initBanDau(){
        
        SanPhamDAO.loadAll();
        tbSP.setDefaultEditor(Object.class, null);
        tbSP.setSelectionMode(0);
        
        
        
        SizeDAO.loadAll();
        KieuDangDAO.loadAll();
        ChatLieuDAO.loadAll();
        MauSacDAO.loadAll();
        LoaiSPDAO.loadAll();
        
        initCbo();
        
        loadSP();
        
    }
    private void loadSP() {
        DefaultTableModel model = new DefaultTableModel();
        Vector data = new Vector();
        Vector<String> tieuDe = new Vector<String>();
        tieuDe.add("Mã sản phẩm");
        tieuDe.add("Tên sản phẩm");
        tieuDe.add("Giá bán");
        tieuDe.add("Số lượng");
        tieuDe.add("Trạng thái");
        tieuDe.add("Size");
        tieuDe.add("Kiểu dáng");
        tieuDe.add("Chất liệu");
        tieuDe.add("Màu sắc");
        tieuDe.add("Hình");
        tieuDe.add("Loại");

        List<SANPHAM> dsMA = SanPhamDAO.showSANPHAM("", 0);
        for (SANPHAM ma : dsMA) {
            Vector<Object> v = new Vector<>();
            v.add(ma.getMa());
            v.add(ma.getTen());
            v.add(String.valueOf(ma.getGiaban()));
            v.add(ma.getSoluong());
            v.add(ma.getTrangthai());
            v.add(ThamChieuDAO.getTENSIZEbyMASIZE(ma.getSize()));
            v.add(ThamChieuDAO.getTENKIEUDANGbyMAKIEUDANG(ma.getKieudang()));
            v.add(ThamChieuDAO.getTENCHATLIEUbyMACHATLIEU(ma.getChatlieu()));
            v.add(ThamChieuDAO.getTENMAUSACbyMAMAUSAC(ma.getMausac()));
            v.add(ma.getHinhanh());
            v.add(ThamChieuDAO.getTENLOAIbyMALOAI(ma.getLoaisp()));
            data.add(v);
        }

        if (data != null) {
            model.setDataVector(data, tieuDe);
        }
        tbSP.setModel(model);
        
        if(tbSP.getRowCount()>0){
            txtMa.setText((String) model.getValueAt(0, 0));
            txtTen.setText((String) model.getValueAt(0, 1));
            txtGia.setText(model.getValueAt(0, 2) + "");
            tenHinh = (String) model.getValueAt(0, 9);
            ImageIcon hinh = new ImageIcon(new ImageIcon("src/cuahanganphuoc/icon/" + tenHinh).getImage().getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_DEFAULT));
            lblHinh.setIcon(hinh);
            txtSoLuong.setText(model.getValueAt(0, 3).toString());
            txtTrangThai.setText(model.getValueAt(0, 4).toString());
        }
    }
    void clear(){
        txtTen.setText("");
        txtMa.setText("");
        txtGia.setText("");
        txtTrangThai.setText("");

    }
    void initCbo(){
        for(SIZE s : LUUTRU.listSize){
            cboSize.addItem(s);
        }
        for(KIEUDANG s : LUUTRU.listKieDang){
            cboKieuDang.addItem(s);
        }
        for(CHATLIEU s : LUUTRU.listChatLieu){
            cboChatLieu.addItem(s);
        }
        for(MAUSAC s : LUUTRU.listMauSac){
            cboMauSac.addItem(s);
        }
        for(LOAISP s : LUUTRU.listLoaiSp){
            cboLoaiSanPham.addItem(s);
        }
    }
    void validateInputs() {
        String ma = txtMa.getText().trim();
         String ten = txtTen.getText().trim();
        String email = txtGia.getText().trim();
        String sdt = txtTrangThai.getText().trim();
        String sl = txtSoLuong.getText().trim();
    
         if (ma.isEmpty() || ten.isEmpty() || email.isEmpty() || sdt.isEmpty() || sl.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        throw new IllegalArgumentException("Vui lòng nhập đủ thông tin.");
         }
         try{
             int gia = Integer.parseInt(email);
             int tt = Integer.parseInt(sdt);
         }catch( Exception e){
             JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng các trường số.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        throw new IllegalArgumentException("Vui lòng nhập đúng định dạng các trường số.");
         }
    }
}
