/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuahanganphuoc.GUI.user;

import cuahanganphuoc.DAO.UserDAO;
import java.awt.Button;
import java.awt.Color;
import java.text.Normalizer;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class MainUser extends javax.swing.JFrame {
    JFrame activeJFrame = null;

    /**
     * Creates new form Home
     */
    public MainUser() {
        initComponents();
        clearMenu();
        openChildJFrame(new Welcome());
        activeJFrame = null;
        btnUser.setText(UserDAO.userDangDangNhap);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnAboutUs = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnChilds = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1370, 750));
        setMinimumSize(new java.awt.Dimension(1370, 750));
        setPreferredSize(new java.awt.Dimension(1370, 750));
        setSize(new java.awt.Dimension(1370, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnOrder.setBackground(new java.awt.Color(204, 0, 0));
        btnOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setText("ORDER");
        btnOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrder);

        btnProduct.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnProduct.setText("PRODUCT");
        btnProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        jPanel1.add(btnProduct);

        btnCustomer.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCustomer.setText("CUSTOMER");
        btnCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomer);

        btnAboutUs.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAboutUs.setText("ABOUT US");
        btnAboutUs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });
        jPanel1.add(btnAboutUs);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 1370, 50);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnUser.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnUser.setForeground(new java.awt.Color(236, 31, 38));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/icon/user.png"))); // NOI18N
        btnUser.setText("Nhân viên 1");
        btnUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnUser);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(1190, 0, 180, 60);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 31, 38));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/icon/logo.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 31, 38));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AN PHUOC STORE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1190, 60);

        pnChilds.setBackground(new java.awt.Color(255, 255, 255));
        pnChilds.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(pnChilds);
        pnChilds.setBounds(0, 110, 1370, 640);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        clearMenu();
        openChildJFrame(new Product());
        clickMenu(btnProduct);
        activeJFrame = null;
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        clearMenu();
        openChildJFrame(new AboutUs());
        clickMenu(btnAboutUs);
        activeJFrame = null;
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        clearMenu();
        openChildJFrame(new Customer());
        clickMenu(btnCustomer);
        activeJFrame = null;
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        clearMenu();
        openChildJFrame(new Order());
        clickMenu(btnOrder);
        activeJFrame = null;
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất?")==JOptionPane.OK_OPTION){
            Login frm = new Login();
            this.dispose();
            frm.setVisible(true);
            frm.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainUser frm = new MainUser();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnChilds;
    // End of variables declaration//GEN-END:variables

    
    void openChildJFrame(JFrame childJFrame)
    {
        if (activeJFrame != null)
        {
            activeJFrame.dispose();
        }
        else
        {
            activeJFrame = childJFrame;
            childJFrame.setBounds(0, 0, pnChilds.getWidth(), pnChilds.getHeight());
            pnChilds.removeAll();
            pnChilds.add(activeJFrame.getContentPane());
            pnChilds.revalidate();
            pnChilds.repaint();
        }
    }
    void clearMenu()
    {
        btnOrder.setBackground(Color.white);
        btnOrder.setForeground(Color.black);
        btnProduct.setBackground(Color.white);
        btnProduct.setForeground(Color.black);
        btnCustomer.setBackground(Color.white);
        btnCustomer.setForeground(Color.black);
        btnAboutUs.setBackground(Color.white);
        btnAboutUs.setForeground(Color.black);
        btnUser.setBackground(Color.white);
        btnUser.setForeground(Color.black);
    }
    void clickMenu(JButton btn){
        btn.setBackground(Color.red.darker());
        btn.setForeground(Color.white);
    }
}
