/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuahanganphuoc.GUI.user;

import cuahanganphuoc.DAO.CTDHDAO;
import cuahanganphuoc.DAO.ChatLieuDAO;
import cuahanganphuoc.DAO.DonHangDAO;
import cuahanganphuoc.DAO.KhachHangDAO;
import cuahanganphuoc.DAO.KieuDangDAO;
import cuahanganphuoc.DAO.LoaiSPDAO;
import cuahanganphuoc.DAO.MauSacDAO;
import cuahanganphuoc.DAO.SanPhamDAO;
import cuahanganphuoc.DAO.SizeDAO;
import cuahanganphuoc.DAO.ThamChieuDAO;
import cuahanganphuoc.MODAL.CT_DONHANG;
import cuahanganphuoc.MODAL.DONHANG;
import cuahanganphuoc.MODAL.KHACHHANG;
import cuahanganphuoc.MODAL.LOAISP;
import cuahanganphuoc.MODAL.LUUTRU;
import cuahanganphuoc.MODAL.SANPHAM;
import cuahanganphuoc.MODAL.SANPHAMTAMTHOI;
import java.awt.Color;
import java.awt.Image;
import java.text.NumberFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Product extends javax.swing.JFrame {
    DefaultTableModel dtm = new DefaultTableModel();
    String tenHinh = "";
    Vector<String> tieuDe = new Vector<String>();
    int TrangThaiSapXep = 1;
    String txtDangSearch = "";
    List<SANPHAMTAMTHOI> listDonHang = new ArrayList<>();
    boolean isKH=false;
    int dongDonHangDangChon=-1;

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
        SanPhamDAO.loadAll();
        MauSacDAO.loadAll();
        ChatLieuDAO.loadAll();
        KieuDangDAO.loadAll();
        SizeDAO.loadAll();
//        LoaiSPDAO
        initBanDau();
         tblDanhSachSanPham.setModel(dtm); 
         loadSP("", 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDanhMuc = new javax.swing.JList<>();
        btnShowAllDanhMuc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachSanPham = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSapXepTheoGia = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtHinhAnh = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPhamTrongDonHang = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnThanhToan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtMaSanPhamChinhSua = new javax.swing.JLabel();
        txtSoLuongChinhSua = new javax.swing.JTextField();
        btnCapNhatChinhSua = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtKhachHang = new javax.swing.JTextField();
        btnCheckKhachHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1370, 640));
        setMinimumSize(new java.awt.Dimension(1370, 640));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 3));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH MỤC");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 210, 70);

        lstDanhMuc.setBorder(null);
        lstDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDanhMucMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstDanhMuc);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 100, 200, 480);

        btnShowAllDanhMuc.setText("Show all");
        btnShowAllDanhMuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        btnShowAllDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllDanhMucActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowAllDanhMuc);
        btnShowAllDanhMuc.setBounds(10, 70, 200, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblDanhSachSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblDanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ma san pham", "Ten san pham", "Hinh anh", "Gia ban", "So luong", "Size", "Chat lieu", "Mau sac", "Kieu dang"
            }
        ));
        tblDanhSachSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachSanPham);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 31, 38));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DANH SÁCH SẢN PHẨM");

        btnSapXepTheoGia.setBackground(new java.awt.Color(236, 31, 38));
        btnSapXepTheoGia.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSapXepTheoGia.setForeground(new java.awt.Color(255, 255, 255));
        btnSapXepTheoGia.setText("Sắp xếp theo giá");
        btnSapXepTheoGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepTheoGiaActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/icon/search.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHinhAnh.setText("hinh anh");

        jLabel4.setText("Mã sản phẩm: ");

        jLabel5.setText("Tên sản phẩm: ");

        jLabel6.setText("Đon giá:");

        jLabel7.setText("Số lượng mua: ");

        txtMaSanPham.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtMaSanPham.setText("MA...");

        txtTenSanPham.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtTenSanPham.setText("Áo ...");

        txtDonGia.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtDonGia.setText("1890000");

        btnThem.setBackground(new java.awt.Color(236, 31, 38));
        btnThem.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("THÊM >");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoLuong)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMaSanPham))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTenSanPham))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtDonGia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35))))
                    .addComponent(txtHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSapXepTheoGia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSapXepTheoGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ĐƠN HÀNG");

        tblSanPhamTrongDonHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        tblSanPhamTrongDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ma san pham", "Ten san pham", "So luong", "Don gia", "Thanh tien"
            }
        ));
        tblSanPhamTrongDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamTrongDonHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanPhamTrongDonHang);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        btnThanhToan.setBackground(new java.awt.Color(0, 51, 204));
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setText("Tổng tiền:");

        txtTongTien.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtTongTien.setForeground(new java.awt.Color(0, 51, 204));
        txtTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTongTien.setText("VND");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)), "Chỉnh sửa số lượng"));

        txtMaSanPhamChinhSua.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtMaSanPhamChinhSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMaSanPhamChinhSua.setText("SP001");

        txtSoLuongChinhSua.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtSoLuongChinhSua.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCapNhatChinhSua.setBackground(new java.awt.Color(0, 51, 204));
        btnCapNhatChinhSua.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatChinhSua.setText("Cập nhật");
        btnCapNhatChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatChinhSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMaSanPhamChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtSoLuongChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCapNhatChinhSua, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSanPhamChinhSua)
                    .addComponent(txtSoLuongChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhatChinhSua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 2));

        jLabel12.setText("Sdt khách hàng: ");

        btnCheckKhachHang.setBackground(new java.awt.Color(0, 51, 204));
        btnCheckKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckKhachHang.setText("Check");
        btnCheckKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckKhachHang)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckKhachHang))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSanPhamMouseClicked
        int row = tblDanhSachSanPham.getSelectedRow();
        txtMaSanPham.setText((String) dtm.getValueAt(row, 0));
        txtTenSanPham.setText((String) dtm.getValueAt(row, 1));
        txtDonGia.setText(dtm.getValueAt(row, 2) + "");
        tenHinh = (String) dtm.getValueAt(row, 8);
        txtSoLuong.setText("1");
        ImageIcon hinh = new ImageIcon(new ImageIcon("src/cuahanganphuoc/icon/" + tenHinh).getImage().getScaledInstance(txtHinhAnh.getWidth(), txtHinhAnh.getHeight(), Image.SCALE_DEFAULT));
        txtHinhAnh.setIcon(hinh);
    }//GEN-LAST:event_tblDanhSachSanPhamMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        txtDangSearch = txtSearch.getText().toString();
        lstDanhMuc.clearSelection();
        loadSP(txtDangSearch, 0);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void lstDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDanhMucMouseClicked
        LOAISP loai = lstDanhMuc.getSelectedValue();
        txtDangSearch = loai.getMaLoai();
        loadSP(loai.getMaLoai(), TrangThaiSapXep);
    }//GEN-LAST:event_lstDanhMucMouseClicked

    private void btnShowAllDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllDanhMucActionPerformed
        txtDangSearch="";
        loadSP(txtDangSearch, TrangThaiSapXep);
        lstDanhMuc.clearSelection();
    }//GEN-LAST:event_btnShowAllDanhMucActionPerformed

    private void btnSapXepTheoGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepTheoGiaActionPerformed
        if(TrangThaiSapXep==1){
            TrangThaiSapXep = 2;
            loadSP(txtDangSearch, TrangThaiSapXep);
        }else if(TrangThaiSapXep==2){
            TrangThaiSapXep=1;
            loadSP(txtDangSearch, TrangThaiSapXep);
        }
    }//GEN-LAST:event_btnSapXepTheoGiaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int soluong = Integer.parseInt(txtSoLuong.getText().toString());
        dtm = (DefaultTableModel) tblDanhSachSanPham.getModel();
        int slton = SanPhamDAO.getSoLuongTonTheoMa(txtMaSanPham.getText().toString());
        if(soluong>slton) {
            JOptionPane.showMessageDialog(this, "Sản phẩm tồn kho không đủ số lượng");
            return;
        }
        SANPHAM sp = SanPhamDAO.getSanPhamByMa(txtMaSanPham.getText().toString());
        
        for(SANPHAMTAMTHOI sptt : listDonHang){
            if(sptt.getMaString().equals(sp.getMa())){
                if(sptt.getSoLuong()+soluong>slton){
                    JOptionPane.showMessageDialog(this, "Sản phẩm tồn kho không đủ số lượng");
                    return;
                }
                listDonHang.add(new SANPHAMTAMTHOI(sp.getMa(), sp.getTen(), sptt.getSoLuong()+soluong, sp.getGiaban()));
                listDonHang.remove(sptt);
                initTableDonHang();
                return;
            }
        }
        
        SANPHAMTAMTHOI sp1;
        sp1 = new SANPHAMTAMTHOI(sp.getMa(), sp.getTen(), soluong, sp.getGiaban());
        listDonHang.add(sp1);
        initTableDonHang();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCheckKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckKhachHangActionPerformed
        try{
            int sdt = Integer.parseInt(txtKhachHang.getText().toString());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ");
            txtKhachHang.setForeground(Color.red);
            isKH=false;
            return;
        }
        KHACHHANG kh = KhachHangDAO.getKhachHangBySDT(txtKhachHang.getText().toString());
        if(kh==null){
            JOptionPane.showMessageDialog(this, "Không tồn tại");
            txtKhachHang.setForeground(Color.red);
            isKH=false;
            return;
        }
        txtKhachHang.setForeground(Color.green);
        isKH=true;
    }//GEN-LAST:event_btnCheckKhachHangActionPerformed

    private void btnCapNhatChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatChinhSuaActionPerformed
        for(SANPHAMTAMTHOI sptt : listDonHang){
            if(sptt.getMaString().equals(txtMaSanPhamChinhSua.getText().toString())){
               int sl = Integer.parseInt(txtSoLuongChinhSua.getText().toString());
               SANPHAM sp = SanPhamDAO.getSanPhamByMa(txtMaSanPhamChinhSua.getText().toString());
               if(sl>sp.getSoluong()){
                   JOptionPane.showMessageDialog(this, "Số lượng sản phẩm trong kho không đáp ứng");
                   return;
               }
               if(sptt.getSoLuong()==sl){
                   JOptionPane.showMessageDialog(this, "Không thay đổi");
                   return;
               }
               if(sl==0){
                   listDonHang.remove(sptt);
                   initTableDonHang();
                   return;
               }
               listDonHang.add(new SANPHAMTAMTHOI(sp.getMa(), sp.getTen(), sl, sp.getGiaban()));
               listDonHang.remove(sptt);
               initTableDonHang();
               break;
            }
        }
    }//GEN-LAST:event_btnCapNhatChinhSuaActionPerformed

    private void tblSanPhamTrongDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamTrongDonHangMouseClicked
        int row = tblSanPhamTrongDonHang.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblSanPhamTrongDonHang.getModel();
        txtMaSanPhamChinhSua.setText((String) model.getValueAt(row, 0));
        txtSoLuongChinhSua.setText(String.valueOf(model.getValueAt(row, 2)));
    }//GEN-LAST:event_tblSanPhamTrongDonHangMouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        DONHANG dh = new DONHANG();
        dh.setMaDH(DonHangDAO.taoMaDHMoi());
        if(isKH) {
            KHACHHANG kh = KhachHangDAO.getKhachHangBySDT(txtKhachHang.getText().toString());
            dh.setMaKH(kh.getMa());
        }else dh.setMaKH("");
        dh.setTongTien(Integer.parseInt(txtTongTien.getText().toString()));
        DonHangDAO.themHoaDon(dh);
        for(SANPHAMTAMTHOI sptt : listDonHang){
            CT_DONHANG ct = new CT_DONHANG(dh.getMaDH(), sptt.getMaString(), sptt.getSoLuong(), sptt.getThanhTien());
            CTDHDAO.themCTHoaDon(ct);
            SANPHAM sp = SanPhamDAO.getSanPhamByMa(ct.getMaSP());
            sp.truSoLuong(ct.getSoLuong());
            SanPhamDAO.capNhatCSDL(sp);
            
        }
        listDonHang.clear();
        initTableDonHang();
        JOptionPane.showMessageDialog(this, "OK");
        loadSP("", 0);
        txtMaSanPhamChinhSua.setText("");
        txtSoLuongChinhSua.setText("");
        initTableDonHang();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatChinhSua;
    private javax.swing.JButton btnCheckKhachHang;
    private javax.swing.JButton btnSapXepTheoGia;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowAllDanhMuc;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<LOAISP> lstDanhMuc;
    private javax.swing.JTable tblDanhSachSanPham;
    private javax.swing.JTable tblSanPhamTrongDonHang;
    private javax.swing.JLabel txtDonGia;
    private javax.swing.JLabel txtHinhAnh;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JLabel txtMaSanPham;
    private javax.swing.JLabel txtMaSanPhamChinhSua;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoLuongChinhSua;
    private javax.swing.JLabel txtTenSanPham;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables
    private void loadSP(String key, int sort) {
        dtm.setColumnCount(0);
        Vector data = new Vector();
        tieuDe.add("Mã sản phẩm");
        tieuDe.add("Tên sản phẩm");
        tieuDe.add("Giá bán");
        tieuDe.add("Số lượng");
        tieuDe.add("Size");
        tieuDe.add("Kiểu dáng");
        tieuDe.add("Chất liệu");
        tieuDe.add("Màu sắc");
        tieuDe.add("Hình");

        List<SANPHAM> dsMA = SanPhamDAO.showSANPHAM(key, sort);
        ThamChieuDAO references = new ThamChieuDAO();
        for (SANPHAM ma : dsMA) {
            Vector<Object> v = new Vector<>();
            v.add(ma.getMa());
            v.add(ma.getTen());
            v.add(String.valueOf(ma.getGiaban()));
            v.add(ma.getSoluong());
            v.add(ThamChieuDAO.getTENSIZEbyMASIZE(ma.getSize()));
            v.add(ThamChieuDAO.getTENKIEUDANGbyMAKIEUDANG(ma.getKieudang()));
            v.add(ThamChieuDAO.getTENCHATLIEUbyMACHATLIEU(ma.getChatlieu()));
            v.add(ThamChieuDAO.getTENMAUSACbyMAMAUSAC(ma.getMausac()));
            v.add(ma.getHinhanh());
            data.add(v);
        }

        if (data != null) {
            dtm.setDataVector(data, tieuDe);
        }
        
        if(tblDanhSachSanPham.getRowCount()>0){
            txtMaSanPham.setText((String) dtm.getValueAt(0, 0));
            txtTenSanPham.setText((String) dtm.getValueAt(0, 1));
            txtDonGia.setText(dtm.getValueAt(0, 2) + "");
            tenHinh = (String) dtm.getValueAt(0, 8);
            ImageIcon hinh = new ImageIcon(new ImageIcon("src/cuahanganphuoc/icon/" + tenHinh).getImage().getScaledInstance(txtHinhAnh.getWidth(), txtHinhAnh.getHeight(), Image.SCALE_DEFAULT));
            txtHinhAnh.setIcon(hinh);
            txtSoLuong.setText("1");
        }
    }
    void initBanDau(){
        tblDanhSachSanPham.setDefaultEditor(Object.class, null);
        tblDanhSachSanPham.setSelectionMode(0);
        loadDanhMucLoai();
        KhachHangDAO.loadAll();
        DonHangDAO.loadAll();
        CTDHDAO.loadAll();
        tblSanPhamTrongDonHang.setDefaultEditor(Object.class, null);
        tblSanPhamTrongDonHang.setSelectionMode(0);
    }
    void loadDanhMucLoai(){
        LoaiSPDAO.loadAll();
        DefaultListModel model = new DefaultListModel();
        List<LOAISP> list = new ArrayList<>();
        list = LUUTRU.listLoaiSp;
        for(LOAISP l:list){
            model.addElement(l);
        }
        lstDanhMuc.setModel(model);
        lstDanhMuc.setSelectionMode(0);
    }
    void initTableDonHang(){
        DefaultTableModel model = new DefaultTableModel();
        Vector data1 = new Vector();
        Vector<String> tieuDe1 = new Vector<String>();
        tieuDe1.add("Mã sản phẩm");
        tieuDe1.add("Tên sản phẩm");
        tieuDe1.add("Số lượng");
        tieuDe1.add("Giá bán");
        tieuDe1.add("Thành tiền");
        
        int tong=0;
        for (SANPHAMTAMTHOI ma : listDonHang) {
            Vector<Object> v = new Vector<>();
            v.add(ma.getMaString());
            v.add(ma.getTenString());
            v.add(ma.getSoLuong());
            v.add(ma.getDonGia());
            v.add(ma.getThanhTien());
            data1.add(v);
            tong+= ma.getThanhTien();
        }

        if (data1 != null) {
            model.setDataVector(data1, tieuDe1);
        }
        tblSanPhamTrongDonHang.setModel(model);
        if(tblSanPhamTrongDonHang.getRowCount()>0){
            
            txtMaSanPhamChinhSua.setText((String) model.getValueAt(0, 0));
            txtSoLuongChinhSua.setText(String.valueOf(model.getValueAt(0, 2)));
            dongDonHangDangChon=0;
            txtTongTien.setText(String.valueOf(tong));
        }
        
    }
}
