/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuahanganphuoc.GUI.admin;

import cuahanganphuoc.DAO.CTDHDAO;
import cuahanganphuoc.DAO.DonHangDAO;
import cuahanganphuoc.DAO.KhachHangDAO;
import cuahanganphuoc.DAO.LoaiSPDAO;
import cuahanganphuoc.DAO.SanPhamDAO;
import cuahanganphuoc.DAO.ThamChieuDAO;
import cuahanganphuoc.MODAL.CT_DONHANG;
import cuahanganphuoc.MODAL.DONHANG;
import cuahanganphuoc.MODAL.LOAISP;
import cuahanganphuoc.MODAL.LUUTRU;
import cuahanganphuoc.MODAL.SANPHAM;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frmDonHang extends javax.swing.JFrame {

    DefaultTableModel tblModel = new DefaultTableModel();

    /**
     * Creates new form frmDonHang
     */
    public frmDonHang() {
        initComponents();
        initBanDau();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaDH = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        txtNgayMua = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        btnChiTiet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDH = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTDH = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTongNgay = new javax.swing.JLabel();
        txtTongThang = new javax.swing.JLabel();
        txtTongTienAll = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Mã đơn hàng");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Tên khách hàng");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Ngày mua");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Tổng tiền");

        btnChiTiet.setBackground(new java.awt.Color(255, 51, 0));
        btnChiTiet.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/icon/info.png"))); // NOI18N
        btnChiTiet.setText("Xem chi tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        tblDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDH);

        tblCTDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCTDH);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("THỐNG KÊ ĐƠN HÀNG");

        txtTongNgay.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtTongNgay.setText("Tổng đơn hôm nay: ");

        txtTongThang.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtTongThang.setText("Tổng đơn tháng này: ");

        txtTongTienAll.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtTongTienAll.setText("Tong tien tat ca:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTongNgay)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongThang)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongTienAll)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel4))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgayMua, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addComponent(btnChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)))
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongNgay)
                    .addComponent(txtTongThang)
                    .addComponent(txtTongTienAll))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(txtNgayMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDHMouseClicked
        int row = tblDH.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblDH.getModel();
        txtMaDH.setText(""+model.getValueAt(row, 0));
        txtMaKH.setText(""+model.getValueAt(row, 1));   
        txtNgayMua.setText(""+model.getValueAt(row, 2));
        txtTongTien.setText(""+model.getValueAt(row, 3));

    }//GEN-LAST:event_tblDHMouseClicked

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        String madh = txtMaDH.getText();
        DefaultTableModel model = new DefaultTableModel();
        
        Vector<String> tieuDe1 = new Vector<String>();
        tieuDe1.add("Mã đơn hàng");
        tieuDe1.add("Mã sản phẩm");
        tieuDe1.add("Tên sản phẩm");
        tieuDe1.add("Số lượng ");
        tieuDe1.add("Thành tiền");
        Vector data1 = new Vector();
        for(CT_DONHANG ct : LUUTRU.listCTDH){
            if(ct.getMaDH().equals(madh)){
                Vector<Object> v = new Vector<>();
                v.add(ct.getMaDH());
                v.add(ct.getMaSP());
                v.add(SanPhamDAO.getTenSanPhamByMa(ct.getMaSP().toString().trim()));
                v.add(ct.getSoLuong());
                v.add(ct.getThanhTien());
                data1.add(v);
            }
        }
        if (data1 != null) {
            model.setDataVector(data1, tieuDe1);
        }
        tblCTDH.setModel(model);
    }//GEN-LAST:event_btnChiTietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDonHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCTDH;
    private javax.swing.JTable tblDH;
    private javax.swing.JTextField txtMaDH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtNgayMua;
    private javax.swing.JLabel txtTongNgay;
    private javax.swing.JLabel txtTongThang;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JLabel txtTongTienAll;
    // End of variables declaration//GEN-END:variables
    void initBanDau(){
        KhachHangDAO.loadAll();
        DonHangDAO.loadAll();
        CTDHDAO.loadAll();
        tblDH.setDefaultEditor(Object.class, null);
        tblDH.setSelectionMode(0);
        tblCTDH.setDefaultEditor(Object.class, null);
        tblCTDH.setSelectionMode(0);
        loadSP();
        txtMaDH.setEditable(false);
        txtMaKH.setEditable(false);
        txtNgayMua.setEditable(false);
        txtTongTien.setEditable(false);
        int tongthang =0;
        int tongngay=0;
        int tongall=0;
        Date now = new Date();
        for(DONHANG dh : LUUTRU.listDonHang){
            if(dh.getNgayMua().getDate()==now.getDate() && dh.getNgayMua().getMonth()==now.getMonth()&& dh.getNgayMua().getYear()==now.getYear()){
                tongngay+=dh.getTongTien();
            }
            if(dh.getNgayMua().getMonth()==now.getMonth()&& dh.getNgayMua().getYear()==now.getYear()){
                tongthang+=dh.getTongTien();
            }
            tongall+=dh.getTongTien();
        }
        txtTongNgay.setText("Tổng tiền theo ngày: "+tongngay);
        txtTongThang.setText(" - Tổng tiền theo tháng: "+tongthang);
        txtTongTienAll.setText(" - Tổng tiền tất cả: "+tongall);
    }
    private void loadSP() {
        DefaultTableModel model = new DefaultTableModel();
        Vector data = new Vector();
        Vector<String> tieuDe = new Vector<String>();
        tieuDe.add("Mã đơn hàng");
        tieuDe.add("Tên khách hàng");
        tieuDe.add("Ngày mua"); 
        tieuDe.add("Tổng tiền");


        List<DONHANG> dsMA = LUUTRU.listDonHang;
        for (DONHANG ma : dsMA) {
            String ten = ma.getMaDH();
            Date role = ma.getNgayMua();
            int tong = ma.getTongTien();
            
            String tenKH;
            if(ma.getMaKH().trim().length()<=0){
                tenKH = "Khách hàng vãng lãi";
            }
            else {
                tenKH = KhachHangDAO.getTENKHbyMAKH(ma.getMaKH());
            }

            Vector<Object> v = new Vector<>();
            v.add(ten);
            v.add(tenKH);
            v.add(role);
            v.add(tong);

            data.add(v);
        }

        if (data != null) {
            model.setDataVector(data, tieuDe);
        }
        tblDH.setModel(model);
        Clear();
    }
    public void Clear(){
        txtMaDH.setText("");
        txtMaKH.setText("");
        txtNgayMua.setText("");
        txtTongTien.setText("");
        txtMaDH.requestFocus();
    }
}
