/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuahanganphuoc.GUI.admin;

import cuahanganphuoc.DAO.KhachHangDAO;
import cuahanganphuoc.DAO.KieuDangDAO;
import cuahanganphuoc.MODAL.KIEUDANG;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frmKieuDang extends javax.swing.JFrame {
    List<KIEUDANG> list = new ArrayList<>();
    DefaultTableModel tblModel = new DefaultTableModel();
    int TrangThai=0;
    /**
     * Creates new form frmKieuDang
     */
    public frmKieuDang() {
        initComponents();
        initTable();
        tblKieuDang.setDefaultEditor(Object.class, null);
        tblKieuDang.setSelectionMode(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKieuDang = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtMaKieuDang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenKieuDang = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblKieuDang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã kiểu dáng", "Tên kiểu dáng"
            }
        ));
        tblKieuDang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKieuDangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKieuDang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 390, 453));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/add1.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 130, 71));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/data-processing.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 140, 69));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, 110, 71));
        getContentPane().add(txtMaKieuDang, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 143, -1));

        jLabel1.setText("Mã kiểu dáng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        jLabel2.setText("Tên kiểu dáng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, -1));
        getContentPane().add(txtTenKieuDang, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 140, -1));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1200, 290));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("QUẢN LÝ KIỂU DÁNG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 590, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(TrangThai!=1){
            TrangThai=1;
            txtMaKieuDang.setText("");
            txtTenKieuDang.setText("");
            KieuDangDAO.loadAll();
            txtMaKieuDang.setText(KieuDangDAO.taoMaKHMoi());
            return;
        }
       try {
        validateInputs(); // Call validation method before proceeding

        String ma = txtMaKieuDang.getText().toString();
        String ten = txtTenKieuDang.getText().toString();
        KieuDangDAO dao = new KieuDangDAO();
        if(dao.themKieuDang(ma, ten)) {
            JOptionPane.showMessageDialog(this, "INSERT THÀNH CÔNG");
            Clear();
        } else {
            JOptionPane.showMessageDialog(this, "Insert thất bại");
        }
        initTable();
    } catch (IllegalArgumentException ex) {
    }
       TrangThai=0;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng UPDATE");
            return;
        }
        try{
            validateInputs();
        }catch(Exception e){
            return;
        }
        String ma = txtMaKieuDang.getText().toString();
        String ten = txtTenKieuDang.getText().toString();
        KieuDangDAO  dao = new KieuDangDAO();
        if (dao.suaKieuDang(ten,ma)) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            Clear();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        initTable();
        TrangThai=0;
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng DELETE");
            return;
        }
        String ma = txtMaKieuDang.getText().toString();
        KieuDangDAO  dao = new KieuDangDAO();
        if (dao.xoaKieuDang(ma)) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
             Clear();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
        initTable();
        TrangThai=0;
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblKieuDangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKieuDangMouseClicked
        // TODO add your handling code here:
        
        int row = tblKieuDang.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblKieuDang.getModel();
        txtMaKieuDang.setText(model.getValueAt(row, 0).toString());
        txtTenKieuDang.setText(model.getValueAt(row, 1).toString());
        TrangThai=2;
    }//GEN-LAST:event_tblKieuDangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKieuDang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKieuDang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKieuDang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKieuDang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKieuDang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKieuDang;
    private javax.swing.JTextField txtMaKieuDang;
    private javax.swing.JTextField txtTenKieuDang;
    // End of variables declaration//GEN-END:variables
     public void initTable() {
        KieuDangDAO kddao = new KieuDangDAO();
        list = kddao.layDanhSachKieuDang();
        tblModel = (DefaultTableModel) tblKieuDang.getModel();
        tblModel.setRowCount(0);  // Clear existing rows

        for (KIEUDANG kieuDang : list) {
            Object[] row = new Object[]{
                kieuDang.getMaKD(), 
                kieuDang.getTenKD()
            };
            tblModel.addRow(row);
        }

        tblKieuDang.setModel(tblModel);
    }
    public void Clear(){
        txtMaKieuDang.setText("");
        txtTenKieuDang.setText("");
        txtMaKieuDang.requestFocus();
    }
    void validateInputs() {
    String ma = txtMaKieuDang.getText().trim();
    String ten = txtTenKieuDang.getText().trim();
    
    if (ma.isEmpty() || ten.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        throw new IllegalArgumentException("Vui lòng nhập đủ thông tin.");
    }
}
}
