/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuahanganphuoc.GUI.admin;

import cuahanganphuoc.DAO.ChatLieuDAO;
import cuahanganphuoc.DAO.KhachHangDAO;
import cuahanganphuoc.MODAL.CHATLIEU;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frnChatLieu extends javax.swing.JFrame {
    List<CHATLIEU> list = new ArrayList<>();
    DefaultTableModel tblModel = new DefaultTableModel();
    int TrangThai = 0;
    /**
    /**
     * Creates new form frnChatLieu
     */
    public frnChatLieu() {
        initComponents();
        initTable();
        tblChatLieu.setDefaultEditor(Object.class, null);
        tblChatLieu.setSelectionMode(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblChatLieu = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaChatLieu = new javax.swing.JTextField();
        txtTenChatLieu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChatLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã chất liệu", "Tên chất liệu"
            }
        ));
        tblChatLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChatLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChatLieu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 473));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/add1.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 120, 72));

        jLabel1.setText("Mã chất liệu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, -1, -1));

        jLabel2.setText("Tên chất liệu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, -1, -1));
        getContentPane().add(txtMaChatLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 200, 33));
        getContentPane().add(txtTenChatLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 200, 33));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản lý chất liệu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 803, 63));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 120, 72));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahanganphuoc/iconadmin/data-processing.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 130, 72));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1360, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       if(TrangThai!=1){
            TrangThai=1;
            txtMaChatLieu.setText("");
            txtTenChatLieu.setText("");
            ChatLieuDAO.loadAll();
            txtMaChatLieu.setText(ChatLieuDAO.taoMaKHMoi());
            return;
        }
        try {
        validateInputs();
        String ma = txtMaChatLieu.getText().trim();
        String ten = txtTenChatLieu.getText().trim();
        ChatLieuDAO dao = new ChatLieuDAO();
        if(dao.themChatLieu(ma, ten)) {
            JOptionPane.showMessageDialog(this, "INSERT THÀNH CÔNG");
            Clear();
        } else {
            JOptionPane.showMessageDialog(this, "Insert thất bại");
        }
        initTable();
    } catch (IllegalArgumentException ex) {
       
    }
        TrangThai=0;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng UPDATE");
            return;
        }
        try{
            validateInputs();
        } catch(Exception e ){
            return;
        }
        String ma = txtMaChatLieu.getText();
        String ten = txtTenChatLieu.getText();
        ChatLieuDAO dao = new ChatLieuDAO();
        if (dao.suaChatLieu(ten,ma)) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            Clear();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        initTable();
        TrangThai=0;
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(TrangThai!=2){
            JOptionPane.showMessageDialog(this, "Chưa sẵn sàng DELETE");
            return;
        }
        String ma = txtMaChatLieu.getText();
        ChatLieuDAO dao = new ChatLieuDAO();
        if (dao.xoaChatLieu(ma)) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            Clear();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
        initTable();
        TrangThai=0;
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblChatLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChatLieuMouseClicked
        // TODO add your handling code here:
         int row = tblChatLieu.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblChatLieu.getModel();
        txtMaChatLieu.setText(model.getValueAt(row, 0).toString());
        txtTenChatLieu.setText(model.getValueAt(row, 1).toString());
        TrangThai=2;
    }//GEN-LAST:event_tblChatLieuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frnChatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frnChatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frnChatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frnChatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frnChatLieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChatLieu;
    private javax.swing.JTextField txtMaChatLieu;
    private javax.swing.JTextField txtTenChatLieu;
    // End of variables declaration//GEN-END:variables
    public void initTable() {
        ChatLieuDAO cldao = new ChatLieuDAO();
        list = cldao.layDanhSachChatLieu();
        tblModel = (DefaultTableModel) tblChatLieu.getModel();
        tblModel.setRowCount(0);  // Clear existing rows

        for (CHATLIEU chatlieu : list) {
            Object[] row = new Object[]{
                chatlieu.getMaCL(), 
                chatlieu.getTenCL()
            };
            tblModel.addRow(row);
        }

        tblChatLieu.setModel(tblModel);
    }
     public void Clear(){
        txtMaChatLieu.setText("");
        txtTenChatLieu.setText("");
        txtMaChatLieu.requestFocus();
    }
    void validateInputs() {
    String ma = txtMaChatLieu.getText().trim();
    String ten = txtTenChatLieu.getText().trim();
    
    if (ma.isEmpty() || ten.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        throw new IllegalArgumentException("Vui lòng nhập đủ thông tin.");
    }
}
}
